baseURL = "https://laserkittens.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Laser Kittens"
theme = "papercss-hugo-theme"
googleAnalytics = ""
copyright = "This work is licensed under a Creative Commons Attribution 4.0 International License."

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  homeMetaContent = "Cyber cyber cyber is meowzek to my ears and blockchain tacos are yummy"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4

